### ISSUE TITLE
Date issue

### ISSUE THREAD

**Issue by Silviu-Surcica** [rubenfiszel/autochangelog-action#13]
Hello, there is an issue with january. It is displayed as 0 instead of 01. (15-0-2020)
Another thing:
All changes so far appear as ## Unclassified Changes. When should it be something else ?

**Comment by rubenfiszel** [comment]
Thanks for the issue.

If that's so then it is possible that the getMonth (here)[https://github.com/rubenfiszel/autochangelog-action/blob/master/src/main.ts#L249] is indexed from 0. Will fix shortly

If it appears as Unclassified changes, it means that the commits header have not been parsed as respecting the conventional commit format: https://www.conventionalcommits.org/en/v1.0.0-beta.4/

**Comment by rubenfiszel** [comment]
The date part is fixed in latest release 0.12.0

If the unclassfied changes persist while respecting the format, please open another issue and paste the `git log` headers

**Comment by Silviu-Surcica** [comment]
Am I not using this right ?
Run rubenfiszel/autochangelog-action@v0.12.0
./manifest.yml ./CHANGES.rst false
Manifest new content:
version: 2.2.2

------
Changelog new content:

# 2.2.2 - 16-0-2020

Thank you for the link on conventional commits. It works if I have the right conventions.

**Comment by rubenfiszel** [comment]
@Silviu-Surcica I botched the release. will release 0.13.0 with the fix. (I applied the fix on the source code but forgot to repackage the dist)
